// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JDoJ4IAfjcXec-TXBEatnC3-GjphEQw',
    appId: '1:160665302186:web:58a3a641ebecd250170cd3',
    messagingSenderId: '160665302186',
    projectId: 'clear-project-123',
    authDomain: 'clear-project-123.firebaseapp.com',
    storageBucket: 'clear-project-123.firebasestorage.app',
    measurementId: 'G-5LNN719JJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8JDoJ4IAfjcXec-TXBEatnC3-GjphEQw',
    appId: '1:160665302186:android:58a3a641ebecd250170cd3',  // Fixed app ID for Android
    messagingSenderId: '160665302186',
    projectId: 'clear-project-123',
    storageBucket: 'clear-project-123.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8JDoJ4IAfjcXec-TXBEatnC3-GjphEQw',
    appId: '1:160665302186:web:58a3a641ebecd250170cd3',
    messagingSenderId: '160665302186',
    projectId: 'clear-project-123',
    authDomain: 'clear-project-123.firebaseapp.com',
    storageBucket: 'clear-project-123.firebasestorage.app',
    measurementId: 'G-T2GYHQRPP8',
  );
}
